node {
    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build code with Maven') {
        withMaven(
            // Maven installation declared in the Jenkins "Global Tool Configuration"
            maven: 'M3') {
            // Run the maven build
            sh "mvn -f services/java-vote-service-redis/pom.xml clean install"
        } 
    }

    stage('Package jar file with Maven into Docker') {
        app = docker.build("sabbour/java-vote-service-redis")
    }

   stage('Push image with Mave to container registry') {
        docker.withRegistry('https://sabbour.azurecr.io', 'acr-hub-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
}